apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-gemma-deployment
  labels:
    app: embedding-gemma
spec:
  selector:
    matchLabels:
      app: embedding-gemma
  template:
    metadata:
      labels:
        app: embedding-gemma
    spec:
      containers:
      - name: embedding-gemma
        image: ghcr.io/ggml-org/llama.cpp:server-cuda
        imagePullPolicy: IfNotPresent # Default value
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
        args:
        - "-m"
        - "/models/ggml-org/embeddinggemma-300M-GGUF/embeddinggemma-300M-Q8_0.gguf"
        - "--embedding"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        - "--n-gpu-layers"
        - "99"
        volumeMounts:
        - name: embedding-gemma-model-storage
          mountPath: /models
      volumes:
      - name: embedding-gemma-model-storage
        persistentVolumeClaim:
          claimName: hdd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-gemma-service
spec:
  selector:
    app: embedding-gemma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000