apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-gemma-deployment
  labels:
    app: embedding-gemma
spec:
  selector:
    matchLabels:
      app: embedding-gemma
  template:
    metadata:
      labels:
        app: embedding-gemma
    spec:
      containers:
      - name: embedding-gemma
        image: ai/embeddinggemma-vllm:300M
        imagePullPolicy: IfNotPresent # Default value
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 12434
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-gemma-service
spec:
  selector:
    app: embedding-gemma
  ports:
  - protocol: TCP
    port: 12434
    targetPort: 12434