apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-next-deployment
  labels:
    app: qwen3-next
spec:
  selector:
    matchLabels:
      app: qwen3-next
  template:
    metadata:
      labels:
        app: qwen3-next
    spec:
      volumes:
      - name: qwen3-next-model-storage
        persistentVolumeClaim:
          claimName: hdd-pvc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "4Gi"
      containers:
      - name: qwen3-next
        image: vllm/vllm-openai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args: 
        - | 
          vllm serve \
          --model /root/.cache/huggingface/lmstudio-community/Qwen3-4B-Instruct-2507-GGUF/Qwen3-4B-Instruct-2507-Q4_K_M.gguf \
          --served-model-name Qwen/Qwen3-4B-Instruct-2507 \
          --gpu-memory-utilization 0.75 \
          --dtype float16 \
          --max-model-len 4096 \
          --enforce-eager
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: qwen3-next-model-storage
          mountPath: /root/.cache/huggingface
        - name: dshm
          mountPath: /dev/shm
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-next-service
spec:
  selector:
    app: qwen3-next
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000