apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdd-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/hdd_models"
  