apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: local