apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-deployment
  labels:
    app: asr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
      - name: asr
        image: fedirz/faster-whisper-server:latest-cuda
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: asr-configmap
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: asr-configmap
              key: PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: asr-configmap
              key: TZ
        - name: ASR_MODEL
          valueFrom:
            configMapKeyRef:
              name: asr-configmap
              key: ASR_MODEL
        - name: ASR_COMPUTE_TYPE
          valueFrom:
            configMapKeyRef:
              name: asr-configmap
              key: ASR_COMPUTE_TYPE
        - name: ASR_LOGGING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: logging-endpoints-configmap
              key: ASR
        volumeMounts:
        - name: asr-model-storage
          mountPath: /root/.cache/huggingface
      - name: kafka-asr
        image: kafka-sidecar:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "kafka-asr.py"]
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints-configmap
              key: KAFKA_URL
        - name: TOPIC_TO_PRODUCE
          valueFrom:
            configMapKeyRef:
              name: kafka-topics-configmap
              key: USER_QUERY
        - name: MY_POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: asr-logging
          mountPath: "/data/logging"
      volumes:
      - name: asr-model-storage
        persistentVolumeClaim:
          claimName: hdd-pvc
      - name: asr-logging
        hostPath:
          path: "/logging"
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: asr-service
spec:
  selector:
    app: asr
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000