apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deployment
  labels:
    app: llm
spec:
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      volumes:
      - name: llm-model-storage
        persistentVolumeClaim:
          claimName: hdd-pvc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "4Gi"
      containers:
      - name: llm
        image: vllm/vllm-openai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args: 
        - | 
          vllm serve \
          --model /root/.cache/huggingface/lmstudio-community/Qwen3-4B-Instruct-2507-GGUF/Qwen3-4B-Instruct-2507-Q4_K_M.gguf \
          --served-model-name Qwen/Qwen3-4B-Instruct-2507 \
          --gpu-memory-utilization 0.8 \
          --dtype float16 \
          --max-model-len 2048 \
          --enforce-eager
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: llm-model-storage
          mountPath: /root/.cache/huggingface
        - name: dshm
          mountPath: /dev/shm
      - name: kafka-llm
        image: kafka-sidecar:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "kafka-llm.py"]
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints-configmap
              key: KAFKA_URL
        - name: TOPIC_TO_CONSUME
          valueFrom:
            configMapKeyRef:
              name: kafka-topics-configmap
              key: USER_QUERY
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  type: NodePort
  selector:
    app: llm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30001