apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts-deployment
  labels:
    app: tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
    spec:
      containers:
      - name: tts
        image: kokoro-for-nvidia5060:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8880
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          valueFrom:
            configMapKeyRef:
              name: tts-configmap
              key: NVIDIA_VISIBLE_DEVICES
        - name: CUDA_VISIBLE_DEVICES
          valueFrom:
            configMapKeyRef:
              name: tts-configmap
              key: CUDA_VISIBLE_DEVICES
        - name: USE_GPU
          valueFrom:
            configMapKeyRef:
              name: tts-configmap
              key: USE_GPU
        - name: DEVICE
          valueFrom:
            configMapKeyRef:
              name: tts-configmap
              key: DEVICE
      - name: kafka-tts
        image: kafka-sidecar:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "kafka-tts.py"]
        env:
        - name: TTS_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints-configmap
              key: TTS_URL
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints-configmap
              key: KAFKA_URL
        - name: SHARED_DIR
          valueFrom:
            configMapKeyRef:
              name: tts-configmap
              key: SHARED_DIR
        - name: TOPIC_TO_CONSUME
          valueFrom:
            configMapKeyRef:
              name: kafka-topics-configmap
              key: LLM_RESPONSE
        volumeMounts:
        - name: shared-storage
          mountPath: /audio_files
      volumes:
      - name: shared-storage
        hostPath:
          path: /data_exchange
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: tts-service
spec:
  selector:
    app: tts
  ports:
    - protocol: TCP
      port: 8880
      targetPort: 8880
      