apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoints-configmap
data:
  LLM_URL: "http://llm-service:80/v1"
  TTS_URL: "http://tts-service:8880/v1"
  KAFKA_URL: "kafka-0.kafka-service.kafka.svc.cluster.local:9092"
  