apiVersion: v1
kind: ConfigMap
metadata:
  name: python-script-configmap
data:
  LLM_URL: "http://llm-service:80/v1"
  ASR_URL: "http://asr-service:8000/v1"
  TTS_URL: "http://tts-service:8880/v1"
  SHARED_DIR: "/shared_data"